### ISSUE TITLE
GAK-eval Author Index page

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#101]
There are some empty items on top and bottom of the list:

![image](https://user-images.githubusercontent.com/9748044/42729825-9da415ca-87b2-11e8-996b-cea0cd79659e.png)

**Comment by jedwardwalters** [comment]
@gkiraz This is probably just a result of some messy data. I'll make sure it's cleaned up.

**Comment by jedwardwalters** [comment]
I've cleaned up all the blank author issues. We still need to clean up the duplicate authors, but I'm closing this for now.
