### ISSUE TITLE
GAK-eval Font Menu

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#106]
Replace Serto Batman with Serto Jerusalem (attached).
[Serto Jerusalem-DXH2Ot_2014Version15_DC_GAK.zip](https://github.com/Beth-Mardutho/hugoye-data/files/2195422/Serto.Jerusalem-DXH2Ot_2014Version15_DC_GAK.zip)

![image](https://user-images.githubusercontent.com/9748044/42730140-54462b62-87bb-11e8-9899-97c5de8a7356.png)

**Comment by wsalesky** [comment]
Done. 

@gkiraz This is the  Serto Jerusalem font I already had installed, let me know if it is different from what is in the attachment.
