### ISSUE TITLE
Multiple authors and duplicate entries

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#114]
@wsalesky Anything that has multiple authors is showing up multiple times. You can see it in two different places:
1. Volume Index
<img width="1435" alt="screen shot 2018-07-16 at 11 36 02 am 2" src="https://user-images.githubusercontent.com/11543800/42768228-f69dd3ce-88ec-11e8-920a-2f12da8661ac.png">

2. Author Index
<img width="1435" alt="screen shot 2018-07-16 at 11 37 48 am 2" src="https://user-images.githubusercontent.com/11543800/42768239-fc2a0c40-88ec-11e8-8c46-51f11f905318.png">

**Comment by jedwardwalters** [comment]
The Issue 1 / Issue 2 headings (which you can see on Volume 19) worked perfectly, by the way!
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/volume/19

**Comment by wsalesky** [comment]
When solving one problem creates a new one... thanks, I think I know what is causing this!

**Comment by jedwardwalters** [comment]
@wsalesky This is fixed on the volume page, but it's still happening for me on the author index, even after a hard refresh.

**Comment by wsalesky** [comment]
Odd, this is what I see: 
<img width="1057" alt="screen shot 2018-07-16 at 10 09 19 pm" src="https://user-images.githubusercontent.com/1168206/42792769-f2e76512-8944-11e8-8487-5f31bb8a6685.png">

**Comment by jedwardwalters** [comment]
Huh. Well, maybe my hard refresh didn't actually work. If you're seeing it correctly, I'm sure it's fine.

**Comment by jedwardwalters** [comment]
Very strange: It still looks wrong for me on author index. I checked on firefox, chrome, and safari.

**Comment by wsalesky** [comment]
Are you looking at the dev server? 
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/authors.html?lang=&alpha-filter=B&view=author

**Comment by wsalesky** [comment]
@jedwardwalters good catch. Also,how odd.

**Comment by jedwardwalters** [comment]
@wsalesky It's also still showing on the current issue page for me (though not the volume page for volume 21):
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/current-issue.html

**Comment by wsalesky** [comment]
Working locally until the dev server is back up.

**Comment by wsalesky** [comment]
@jedwardwalters I pretty sure this is solved.

**Comment by jedwardwalters** [comment]
Okay, sounds good. I'll let you know if I spot any irregularities after the server is back up.
