### ISSUE TITLE
Order of titles in individual volumes

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#12]
(I'm having trouble following the email chain, so I'm trying to get organized)

Add `<biblScope type="order" n="#"/>` where # =- the sequential number of the item in that volume.

@wsalesky Does this seem okay?

Would it be helpful for author index if we had a more robust n=#? Such as: 5.1.1 for volume 5, issue 1, item number 1? That way, all results for an individual author could be listed in sequential order from earliest to most recent (or maybe we'd decide to put most recent at the top under author names).

**Comment by wsalesky** [comment]
@jedwardwalters Yes, this makes sense for me. 

Do you want to have a page view for each volume rather then the expanding menu?

**Comment by jedwardwalters** [comment]
I think we covered this in another issue, but yes, I think a page view for each volume would be helpful.

**Comment by jedwardwalters** [comment]
And do you think the more robust numbering system (5.1.1) is necessary? Or should it just be the simple version within each issue? (i.e. n="1")

**Comment by wsalesky** [comment]
I don't think the more robust numbering is necessary. Also, I can't sort it as an integer if you number that way. So I prefer the simpler method.

**Comment by jedwardwalters** [comment]
Got it. Thanks.

**Comment by jedwardwalters** [comment]
@wsalesky I just added this element to the 4 articles in volume 21 for testing, but the webhook failed. It says one of the articles is locked by admin.

**Comment by wsalesky** [comment]
Done. Close if it looks right to you. Next up section headings.

**Comment by jedwardwalters** [comment]
Looks good. Thanks.
