### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#13]
Need to add `<biblScope type="page">##-##</biblScope>` in the` <sourceDesc>`

**Comment by jedwardwalters** [comment]
@wsalesky Do we need the page number to be machine readable? Should I make it:
`<biblScope type="page" from="##" to="##">##-##</biblScope>`?

**Comment by wsalesky** [comment]
@jedwardwalters Yes, to the example above

**Comment by jedwardwalters** [comment]
@wsalesky Okay, thanks.

**Comment by jedwardwalters** [comment]
Yes.
