### ISSUE TITLE
GAK-eval2: Author index

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#138]
Many names have junk ASCII; e.g.

![image](https://user-images.githubusercontent.com/9748044/43040395-7bcba4fa-8d10-11e8-894a-d6cf1bcb92ec.png)

Will this be corrected when volumes 1-11 are fixed?

G

**Comment by jedwardwalters** [comment]
@gkiraz Yes, these will get cleaned up as I edit 5-11 (and other files too).

**Comment by jedwardwalters** [comment]
I'm going to close this for now. We have a more recent issue (#156) about special characters. It has turned out to be a little more complicated than I thought it would be, but we'll get it fixed.
