### ISSUE TITLE
GAK eval2: PDFs missing for "uncorrected transformations" status

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#143]
Can we put the PDFs for these?

![image](https://user-images.githubusercontent.com/9748044/43043361-4497deae-8d60-11e8-953d-bdf003fff5f3.png)

**Comment by wsalesky** [comment]
As long as it is a regular pattern we can script it.

**Comment by jedwardwalters** [comment]
Should be fairly regular. We just need it to match the following formula:
`<idno type="PDF">https://hugoye.bethmardutho.org/pdf/vol21/HV21N1Brock.pdf</idno>`
after the  <title> in the <`sourceDesc><biblStruct><analytic>`

So, there are two variables: the folder for the volume number (right after /pdf) and the final element: the file name. 

See here for example:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1Brock.xml#L42

**Comment by wsalesky** [comment]
I will run it tonight.

**Comment by jedwardwalters** [comment]
@wsalesky The PDF button is showing up, but when you click it, a lot of them return 404 pages rather than starting the download. But randomly a couple of them did actually download.

**Comment by wsalesky** [comment]
@jedwardwalters Which ones don't work, and are they (the pdfs) on the master branch.

**Comment by jedwardwalters** [comment]
I just tested with the first few links from Vol. 11: https://hugoye.bethmardutho.org/volume/11

1st item (Farag): 404
2nd item (Brock): [this article isn't loading at all for some reason -- not just the PDF]
3rd item (Possekel): Worked fine
4th item (Turner): 404
5th item (Heal): 404
6th item (Kitchen): worked fine

And yes, all of these PDFs are on the master, though I need to push over the later volumes (I think the PDFs for volumes 17-21 are only on dev).

**Comment by wsalesky** [comment]
1st item, is incorrectly coded. Not sure how that happened. (See the 'vol21' below)
`https://github.com/Beth-Mardutho/hugoye-data/raw/master/pdf/vol21/HV11N1Farag.pdf`
2nd item I will fix. 
4rd item, does not exist on github
5th item not on github

As a side note, since we are coding the type on the text element of the article I would like to change all the URIs to use the article instead of using the current structure, so: `https://hugoye.bethmardutho.org/bookReview/hv11n1prheal1`
would become
`https://hugoye.bethmardutho.org/article/hv11n1prheal1`

Would you mind? It will simplify some backend stuff.

**Comment by jedwardwalters** [comment]
Ah, okay. Thanks for the follow up on those items.

And that's perfectly fine with me. Whatever makes things simpler for you!

**Comment by wsalesky** [comment]
Okay, I'm going to run that update on the uris now.

**Comment by jedwardwalters** [comment]
I've got a batch of files checked out on a branch that I'm working on. Will that complicate things when I try to merge?

**Comment by wsalesky** [comment]
I think it will be fine, I am only changing the URIs.

**Comment by jedwardwalters** [comment]
Okay. Thanks.

**Comment by wsalesky** [comment]
@jedwardwalters Can I close this?

**Comment by jedwardwalters** [comment]
Yes I think so.
