### ISSUE TITLE
GAK eval2: extra periods in "How to cite" box

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#145]
I think this problem is across articles...

![image](https://user-images.githubusercontent.com/9748044/43043402-1e44ffe2-8d61-11e8-8399-ade0a64c8050.png)

Also,is this supposed to be a "," instead of a period?

![image](https://user-images.githubusercontent.com/9748044/43043410-4211c612-8d61-11e8-9cc3-2fb662fbd968.png)

**Comment by jedwardwalters** [comment]
In the first image I think it's just because there are quotation marks in the actual title of the book, so it's throwing off our system. 

As for the period or comma, I went with the bibliography version of the citation, which calls for a period.

**Comment by jedwardwalters** [comment]
I think I took care of this extra period the other day, but I’m not seeing it reflected. Maybe it was a webhook issue. I can check later tonight.
