### ISSUE TITLE
GAK eval2: images missing from Penn's paper

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#146]
Also, see if this is a general problem across papers or just this one.

![image](https://user-images.githubusercontent.com/9748044/43043419-7763aca4-8d61-11e8-81a3-6714529e4bca.png)

**Comment by wsalesky** [comment]
@jedwardwalters I think this is a data problem.

**Comment by jedwardwalters** [comment]
Yes, image code needs to be standardized by me.

@wsalesky This is our test article, but the images still aren't displaying properly: https://hugoye.bethmardutho.org/report/hv21n1cr-amsterdam

Any ideas?

**Comment by wsalesky** [comment]
@jedwardwalters Those images are on the dev branch. They need to be moved to the master.

**Comment by jedwardwalters** [comment]
Got it. Thanks.

**Comment by jedwardwalters** [comment]
@wsalesky I fixed the code on HV21N1Penn, and most of the images are showing up fine. However, two of them aren't loading in the article (image 2 and image 8). Any ideas on why?

**Comment by wsalesky** [comment]
@jedwardwalters I'm guessing it has to do with the format of the images. the .tiff images are not showing up. .tiff is not widely supported in browsers. 

https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support
Also, they are enormous. Any chance we can convert them to JPEG?

**Comment by jedwardwalters** [comment]
@wsalesky Ah, okay. Yes, I can probably convert them and see if that helps.

**Comment by jedwardwalters** [comment]
Okay, I did that. I think the webhook for the file addition failed though: https://github.com/Beth-Mardutho/hugoye-data/settings/hooks/36537517#delivery-request

**Comment by jedwardwalters** [comment]
I added the jpeg images to the master branch--that's where they should be to appear on the production server right?

**Comment by wsalesky** [comment]
@jedwardwalters I think this is now fixed.

**Comment by jedwardwalters** [comment]
Yep, it looks good (once I finally got it to load this morning!). I'll have to go through and fix images elsewhere, but this issue is solved.
