### ISSUE TITLE
gak eval2: footer logos

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#153]
Replace:
Hugoye: Journal of Syriac Studies is built on the Srophe platform and is hosted by Initiative for Digital Humanities, Media, and Culture, Texas A&M with a mirror hosted by Jean and Alexander Heard Library, Vanderbilt University.

With:
Hugoye: Journal of Syriac Studies is built on the Srophe platform. The development server is hosted by the Jean and Alexander Heard Library, Vanderbilt University.

Logos:
First logo on the left: Srophe, then the Valenderbilt logo. Remove the Texas logo.

@wsalesky : I am correct in my assumption about who is hosting the development server?

![image](https://user-images.githubusercontent.com/9748044/43049319-6da995a4-8dc3-11e8-8bf4-a02adf44a495.png)

**Comment by wsalesky** [comment]
Done.
