### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#161]
@wsalesky Both of my last two commits (both on the same file) have failed on the webhook, and the fail message says something like "the file already exists and you do not have write permission." So I'm not sure what's going on there.

**Comment by wsalesky** [comment]
Try resending them now.

**Comment by jedwardwalters** [comment]
Yes, that worked. However, now we need to redeploy the .xar because the display of the article in question got messed up. Sorry.

**Comment by wsalesky** [comment]
Okay, I updated it. At some point I should go over how to do it with you.

**Comment by jedwardwalters** [comment]
Yeah, that's probably a good idea. And thanks.
