### ISSUE TITLE
Footnote style conversion

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#167]
@wsalesky In the files that were auto converted from html (vols 5-11), it looks like the footnotes were converted into the `<ref target="#FN1">` style (where the notes come at the end) rather than the inline `<note>` style.

I just manually converted one article to the latter style, and it took a long time. I'm wary of asking you to do too many extra things at this point, but is there any way to automate this conversion?

Another option, I suppose, would be to set up the code so that the `<ref target="FN1">` style works in addition to the inline `<note>` style and renders them the same way.

**Comment by wsalesky** [comment]
@jedwardwalters Can you clarify what should happen if I automate this?  With examples from a record that has not been transformed?

**Comment by jedwardwalters** [comment]
Sure. I'll use this file: https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV11N1Kitchen.xml

Here's the first footnote reference in the text: https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV11N1Kitchen.xml#L137
`...madrāshē<ref target="#FN1">1</ref> and...`

And here's what the target looks like:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV11N1Kitchen.xml#L1667

```
<p>
            <ref target="#FNRef1">1</ref> 
            <hi rend="italic">Hymns on Virginity</hi>, numbers
    42-50. Cf. Edmund Beck, CSCO 223/224, Louvain, 1962;
    English translation by Kathleen E. McVey, <hi rend="italic">Ephrem the
    Syrian: Hymns</hi> (The Classics of Western Spirituality; New
    York: Paulist Press, 1989), 438-460. <ref target="#FNRef1">
               <graphic url="../site/RetArrow.gif" rend="img" mimeType="image/gif"/>
            </ref>
</p>
```

Here's what it should look like:
```
...madrāshē<note place="foot" xml:id="ftn1" n="1"><p rend="footnote text">Hymns on Virginity</hi>, numbers
    42-50. Cf. Edmund Beck, CSCO 223/224, Louvain, 1962;
    English translation by Kathleen E. McVey, <hi rend="italic">Ephrem the
    Syrian: Hymns</hi> (The Classics of Western Spirituality; New
    York: Paulist Press, 1989), 438-460.</p></note> and...
```

**Comment by jedwardwalters** [comment]
FYI, for some reason it also duplicates every ref target with a <graphic> element:
```
<ref target="#FNRef1">
               <graphic url="../site/RetArrow.gif" rend="img" mimeType="image/gif"/>
            </ref>
```

**Comment by wsalesky** [comment]
@jedwardwalters I just pushed this conversion in a new branch. It seems to have worked as expected, but please double check, I can always tweak it and run it again. As a note, this only deals with refs that follow the pattern in this issue. 

`<ref target="#FN1">`
referring to:
`<ref target="#FNRef1">`

**Comment by jedwardwalters** [comment]
Thank you! I’m out and about right now, but I will review it this afternoon.

**Comment by jedwardwalters** [comment]
Thanks, @wsalesky !
