### ISSUE TITLE
config file edit

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#173]
@wsalesky I just made a small edit to the config file to add a text type ("announcement") -- but that change isn't showing up on the Volume 11 page yet.

**Comment by jedwardwalters** [comment]
Looks like it was a webhook.

**Comment by wsalesky** [comment]
Fixed, `type="announcement" ` was missing the closing `"` resulting in poorly formed XML.

**Comment by jedwardwalters** [comment]
Argh. Sorry.
