### ISSUE TITLE
Bug in page break display

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-data#175]
See: https://hugoye.bethmardutho.org/exist/apps/hugoye/article/hv21n1kessel
Reported via email. 

XSLT relies on @n attribute in tei:pb, change to display even without number.

**Comment by wsalesky** [comment]
Fixed. Although in some cases there is only a page break at the end of the article, making the toggle seem less useful.

**Comment by jedwardwalters** [comment]
Yes, I think the issue was with the automatic conversion through OxGarage. I just forgot that I need to go back and manually add page numbers. Will do that ASAP.
