### ISSUE TITLE
Question about URIs

### ISSUE THREAD

**Issue by wsalesky** [Beth-Mardutho/hugoye-data#19]
@jedwardwalters 

The template I have uses: https://hugoye.org/
The pdf example uses: https://hugoye.bethmardutho.org/

Which is correct?

**Comment by gkiraz** [comment]
It will be  https://hugoye.bethmardutho.org/

**Comment by jedwardwalters** [comment]
Yes, sorry about that. I forgot to update that on the original template.

**Comment by wsalesky** [comment]
Thanks
