### ISSUE TITLE
Browser tab logo

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#2]
Change the "Theme" tab from the letter tet to he (ܗ) for Hugoye. See attached files.
[ܗ.docx](https://github.com/Beth-Mardutho/hugoye-data/files/1763926/default.docx)
[ܗ.pdf](https://github.com/Beth-Mardutho/hugoye-data/files/1763927/default.pdf)

**Comment by wsalesky** [comment]
moved to app. https://github.com/Beth-Mardutho/hugoye-app/issues/2
