### ISSUE TITLE
PDF files on master branch

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#204]
@wsalesky I meant to ask you this at our meeting, but I forgot: The PDF files for back issues are all on dev branch on GitHub, but they aren't all on Master branch. What's the easiest way to get those in sync?

**Comment by wsalesky** [comment]
Well, I think it is probably time to do a merge from dev into master. I can do it this week.

**Comment by jedwardwalters** [comment]
Okay, sounds good. I think things have slowed down enough from rapid changes that we can do this whenever you are ready.

**Comment by wsalesky** [comment]
@jedwardwalters I have made the updates.

**Comment by jedwardwalters** [comment]
Thanks!
