### ISSUE TITLE
Preview page

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#205]
@wsalesky @jedwardwalters ,
Do we want to keep this page as is when there are no draft articles, or kill the menu item programmatically if there are no drafts in the system?

![image](https://user-images.githubusercontent.com/9748044/43342966-877b4548-91b2-11e8-998c-af9062c72f8e.png)

**Comment by jedwardwalters** [comment]
I think we can just leave it. Since it will auto-populate when we have drafts, it won't be difficult to maintain.

**Comment by wsalesky** [comment]
@gkiraz @jedwardwalters I agree.
