### ISSUE TITLE
Spaces in "P D F" status

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#208]
Is it "P D F" or "PDF". The Status page has "PDF".

I found this problem on this page:
https://hugoye.bethmardutho.org/exist/apps/hugoye/article/hv12n2trigona-harany

I don't know if it is a global or local problem.

![image](https://user-images.githubusercontent.com/9748044/43344570-36be2606-91b8-11e8-9eae-02b7e109e020.png)

**Comment by jedwardwalters** [comment]
@wsalesky I was actually curious about why there are spaces in P D F too. Can we fix that?
