### ISSUE TITLE
TEI for PDF papers

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#209]
@jedwardwalters ,
Do we want to keep the TEI link when the TEI is simply a placeholder?
I am fine with either. Just wanted to raise the issue.

![image](https://user-images.githubusercontent.com/9748044/43344746-d49fb236-91b8-11e8-9807-2ffd2ddb2165.png)

**Comment by jedwardwalters** [comment]
Yes, we might as well keep it. It doesn't hurt anything, and it'll be nice not to have to worry about another variable in our code.

**Comment by wsalesky** [comment]
I agree with @jedwardwalters
