### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#214]
@wsalesky Now that you did a big data merge, do we need to adjust the workflow so that:
1. adjustments to files that are already on the server should be done on the master branch
2. new files are added to the dev branch

I'm asking because @AimeeAH is going through back issues and adding the text type and order information, and she's working off the dev branch.

**Comment by jedwardwalters** [comment]
@wsalesky And this reminds me: which branch do we have hooked up to hugoye.bethmardutho.org? Is it still the dev branch or did you switch it back to master? I just did a couple of small updates on the master branch and the webhooks failed.

**Comment by wsalesky** [comment]
@jedwardwalters @AimeeAH Why don't we carry on as is for now. I will have to switch the webhooks to listen for changes to the master branch, and I can not do it this week. Next week we can switch.

**Comment by jedwardwalters** [comment]
Sounds good, @wsalesky. Thanks.

So, @AimeeAH, keep working on the dev branch, exactly like you've been doing.

**Comment by wsalesky** [comment]
@jedwardwalters It is hooked up to the dev branch, you can merge master into dev to get those changes up.

**Comment by jedwardwalters** [comment]
Ah okay. There were a few other changes that showed up when i looked at the dev - master comparison, so I didn't do a pull request in case it would mess anything up.

**Comment by wsalesky** [comment]
want me to do the merge?

**Comment by jedwardwalters** [comment]
Sure, that'd be great.

**Comment by wsalesky** [comment]
Done. Dev should now be up to date with master

**Comment by jedwardwalters** [comment]
Thank you!

**Comment by jedwardwalters** [comment]
I may be mistaken, but it looks like the webhook on your most recent merge failed (and one I did right after that too).

**Comment by wsalesky** [comment]
Yep, sorry, bad permissions on the git-sync code. Updated and pushed the last two changes.
