### ISSUE TITLE
Article PDF link 404

### ISSUE THREAD

**Issue by nathangibson** [Beth-Mardutho/hugoye-data#232]
Loving the new interface! 

However, when I am at https://hugoye.bethmardutho.org/article/hv13n1prseleznyov and click the PDF button, the link https://github.com/Beth-Mardutho/hugoye-data/raw/master/pdf/vol13/hv13n1prseleznyov.pdf goes to a 404 page. Looks to be a case-sensitive filename issue, since I found the actual article at https://github.com/Beth-Mardutho/hugoye-data/raw/master/pdf/vol13/HV13N1PRSeleznyov.pdf

**Comment by wsalesky** [comment]
Thanks @nathangibson

**Comment by jedwardwalters** [comment]
Thanks for catching that and letting us know, @nathangibson !
