### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#239]
@wsalesky The image size on the article below is huge. What's the easiest way for us to limit this? I know we talked about this in a previous issue that I found, but we never actually settled how to do it.

https://hugoye.bethmardutho.org/article/hv21n2obit-murray

**Comment by jedwardwalters** [comment]
@wsalesky So sorry to bug you, as I'm sure you have other things to do, but I need to get this issue worked out before I can announce the publication of the new issue. Do we have something in place already to control image size?

**Comment by wsalesky** [comment]
@jedwardwalters Sorry, I missed this one this morning. You will need to add a width attribute. ex:

`<graphic url="https://hugoye.bethmardutho.org/resources/images/articles/HV21N2Obit-Murray1.png" width="500px" rend="center">`

**Comment by jedwardwalters** [comment]
It worked great, thanks!
