### ISSUE TITLE
Bibliography stuff

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#240]
@wsalesky I noticed that in the Bibliography section (not just in the current issue) there are some odd things happening. There are some missing spaces between items, and there are often two periods at the end. See here for example:
https://hugoye.bethmardutho.org/article/hv21n2hartung#Head-id.hv21n2hartung.3

I looked at the TEI, and there doesn't appear to be anything there causing this.

**Comment by wsalesky** [comment]
@jedwardwalters Thanks for finding those. I submitted a patch for the two items listed above, if there are any other issues please let me know.
