### ISSUE TITLE
Author line on index pages

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#244]
@wsalesky Would it be much work to move the author (for example: by Sebastian P. Brock) from the end of the title to a new line on the volume index/current volume pages? If you showed me where to go, I could probably even make the edit myself.

So, for example, at the top of this page: https://hugoye.bethmardutho.org/current-issue.html

Mary as a 'Letter': And Some Other Letter Imagery in Syriac Liturgical Texts by Sebastian P. Brock
Source: Hugoye: Journal of Syriac Studies 21.1 (2018): 3-20.
URI: https://hugoye.bethmardutho.org/article/hv21n1brock

would become:

Mary as a 'Letter': And Some Other Letter Imagery in Syriac Liturgical Texts 
By Sebastian P. Brock
Source: Hugoye: Journal of Syriac Studies 21.1 (2018): 3-20.
URI: https://hugoye.bethmardutho.org/article/hv21n1brock

This would be for all the sections, by the way (articles, reviews, obituaries, reports, etc.).

**Comment by wsalesky** [comment]
@jedwardwalters The author display in the summary view is handled here: 
https://github.com/Beth-Mardutho/hugoye-app/blob/master/modules/content-negotiation/tei2html.xqm#L107

You could simply add a <br/> element to this line: https://github.com/Beth-Mardutho/hugoye-app/blob/master/modules/content-negotiation/tei2html.xqm#L109

I will let you take a swing at it. If you run into any problems I can do it, it will only take a minute.

**Comment by wsalesky** [comment]
@jedwardwalters No worries.

**Comment by jedwardwalters** [comment]
Looks great. Thanks.
