### ISSUE TITLE
Webhook fail

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#248]
@wsalesky I was cleaning up some issues with Volume 15, and the webhooks have failed. Not sure why.

**Comment by jedwardwalters** [comment]
Sorry, meant to include this: https://github.com/Beth-Mardutho/hugoye-data/pull/247/commits/7d184e6e6ddfd59e276b4b86cc7b44276f50670a

**Comment by wsalesky** [comment]
The config file was pointing to the dev branch not the master. I changed it. Let me know if you see any problems.
