### ISSUE TITLE
Dashboard uploads

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#251]
Hi @wsalesky, I uploaded the articles for Hugoye volume 22.1, and everything went fine there. However, when I tried to upload the pdfs and the images, I couldn't actually find the folders where they needed to go. Inside the "pdf" folder, only vol15 is visible (see screenshot below). Should I click the "reindex collection" button? I tried clicking the "refresh" button, but that didn't do anything.
<img width="870" alt="Screen Shot 2019-03-08 at 9 36 18 AM" src="https://user-images.githubusercontent.com/11543800/54087271-7d827d00-4327-11e9-9855-74660cdd69f8.png">

**Comment by wsalesky** [comment]
@jedwardwalters I think the images and PDFs are stored on github only, so as not to inflate the data storage in eXist. Are they not showing up on the website?

**Comment by jedwardwalters** [comment]
Oh okay. Yes, I can see the folders on the github website. So should I just add them the old way not using dashboard?

**Comment by wsalesky** [comment]
Yes, just add them to github. Also, all the new TEI records you are adding should be added to github as well, just turn off webhooks for the moment, so you don't have the funny character issue. GitHub should contain the canonical version of the data. Kids are back in school this week, so I will fast track testing the new version of eXist, and see if we can get the apps moved.

**Comment by jedwardwalters** [comment]
Thanks. I still don't fully understand the relationship of GitHub and exist, but that's my problem not yours :)

And to turn off the webhooks, do I just uncheck the active box here (and save changes)?
<img width="764" alt="Screen Shot 2019-03-10 at 1 00 54 PM" src="https://user-images.githubusercontent.com/11543800/54088463-af4e1080-4334-11e9-9717-6529049b4edf.png">

**Comment by jedwardwalters** [comment]
Okay, I added all the files with a branch with the webhook disabled. Thanks!
