### ISSUE TITLE
One small thing

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#254]
@wsalesky This is a really small thing, and not of high priority:

On the new volume 22 page, the articles that don't have both a `<main>` and `<sub>` title still has a colon showing up after the title (see image below). That's not happening (for comparison) on the volume 21 page (see second image).

<img width="746" alt="Screen Shot 2019-03-10 at 8 45 44 PM" src="https://user-images.githubusercontent.com/11543800/54094342-8fd7d780-4376-11e9-8bfc-e16264b61b57.png">
<img width="573" alt="Screen Shot 2019-03-10 at 8 53 01 PM" src="https://user-images.githubusercontent.com/11543800/54094348-936b5e80-4376-11e9-8edd-88b4b1448bf3.png">

**Comment by wsalesky** [comment]
Fixed.
