### ISSUE TITLE
Page layout for reviews

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#260]
@wsalesky Many of the book review pages do not have a left hand column (because there are no headings for the table of contents I assume). This makes the page layout look different as the text spreads all the way over to the left. Is there a way to "force" that column on the left to appear so that the text is centered on the page?

For some reason this review displays correctly even without a TOC:
https://hugoye.bethmardutho.org/review/hv22n2prwalters

Compare with:
https://hugoye.bethmardutho.org/review/hv22n2prbarczok

**Comment by wsalesky** [comment]
Fixed. Always shows a left column now.

**Comment by jedwardwalters** [comment]
Thank you!
