### ISSUE TITLE
webhook fail

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#276]
@wsalesky I just tried updating a file and had to change the filenames of a bunch of images, and the webhook failed. Maybe it's because there were so many files? Can you check it out and let me know if I did something wrong?

**Comment by wsalesky** [comment]
@jedwardwalters Looks like all the images loaded but you have a issue with your XML file: 
```
<response status="fail">
    <message>Failed to update resource /db/apps/hugoye-data/data/tei/HV6N2Clocksin_Fernando.xml: java:org.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (869,11) : The element type "div" must be terminated by the matching end-tag "&lt;/div&gt;". XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (869,11) : The element type "div" must be terminated by the matching end-tag "&lt;/div&gt;".</message>
</response>
```

**Comment by jedwardwalters** [comment]
Weird! Oxygen didn't show me an error before I uploaded it. I'll see what the deal is.

**Comment by jedwardwalters** [comment]
Got it figured out. Thanks.
