### ISSUE TITLE
Info after contributor

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#28]
In the blue box below, the author's name is followed by extra data that probably needs to show somewhere else. Is this a fix we need to do to the converted XMLs, or is something wrong in the display?

![image](https://user-images.githubusercontent.com/9748044/42124934-7535fe10-7c3a-11e8-8381-41ce9fb0398d.png)

**Comment by wsalesky** [comment]
Note to self: XSLT issue.

**Comment by wsalesky** [comment]
Done.
