### ISSUE TITLE
Peer-reviewed button only for papers

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#35]
@wsalesky , the peer-reviewed button should apply only to papers.

Suggestion solutions:

1. If we went for a config file for the ordering of the article types, have an attribute there next to the sections that the peer-reviewed button should apply.

2. Put it in the XMLs that need to show it.

4. Hard-coded for all articles of type "papers" (but I don't like hard coding!)

Thoughts?

G

**Comment by wsalesky** [comment]
@gkiraz This is the application config file:
https://github.com/Beth-Mardutho/hugoye-app/blob/master/repo-config.xml

I will go ahead and add the order for article types with a peer-reviewed yes/no option.

**Comment by wsalesky** [comment]
Added: 
https://github.com/Beth-Mardutho/hugoye-app/blob/master/repo-config.xml#L81

@gkiraz @jedwardwalters I know at least in the generated content there were additional types, not included in this list, they can be listed as sub-types to any of these main types (comma separated list).

**Comment by jedwardwalters** [comment]
@wsalesky Did we decide where exactly we are declaring the article type? I remember talking about it I think, but I don't have it in my template.

**Comment by jedwardwalters** [comment]
Maybe in the `<text>` element?

**Comment by wsalesky** [comment]
right now it is only in the URI. It would probably be useful to put it somewhere else as well. Does the text element have a type attribute? If so, that would work well.

**Comment by jedwardwalters** [comment]
Yes, I just tested and you can use the type attribute on the text element.

**Comment by wsalesky** [comment]
Great lets us that. Let me know when there are some up and I will do the volume view.

**Comment by jedwardwalters** [comment]
Okay. Hoping to have something up for testing by tonight.

**Comment by wsalesky** [comment]
@jedwardwalters I think this can be closed.
