### ISSUE TITLE
Editing html conversion files

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#39]
@wsalesky I just made some edits to one of the files that you auto converted. I did it on the htmlconversion branch, but then the webhook failed, and I'm not sure how to interpret the reason why.

**Comment by jedwardwalters** [comment]
Here's the pull request: https://github.com/Beth-Mardutho/hugoye-data/pull/38

**Comment by wsalesky** [comment]
Webhooks currently only work on the master branch. If you merge them into master it should work.  (Once the new server is set up this will change to the way we are doing the Corpus, dev branch goes to http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/ and master will go to the production website.)

**Comment by jedwardwalters** [comment]
Oh okay. So, as I update files from the htmlconversion branch, I should just move them over to the master branch? Or should we go ahead and bring all of those files over to master?

**Comment by wsalesky** [comment]
Either way is fine, I was uncomfortable putting them on master since I was still playing with the transformation. I think it is safe to move them all if you want.

**Comment by jedwardwalters** [comment]
Ah I see. Can I just merge the whole htmlconversion branch into master? Or is that going to cause other issues?

**Comment by wsalesky** [comment]
That should be fine

**Comment by jedwardwalters** [comment]
Okay, I got them all merged over. I don't think the webhooks are working yet though. It's not catching any of the things I'm changing.

**Comment by wsalesky** [comment]
I will take a look.

**Comment by jedwardwalters** [comment]
Oh yes. They were in folders on that branch and I didn’t change it when it came over. So I can make that change tonight.

**Comment by wsalesky** [comment]
Okay. I have to re deploy after, so new data will be up tonight, late.

**Comment by wsalesky** [comment]
@jedwardwalters Looks like I made a bit of a mess this morning. I will get it sorted out during the day, but if you could hold off on any editing for an hour or two that would be great.

**Comment by jedwardwalters** [comment]
Got it. Thanks for letting me know.

**Comment by wsalesky** [comment]
@jedwardwalters Sorry for the delay I totally messed up a merge. Everything should be good to go now. 

All TEI lives in /data/tei/
All images for articles live in /resources/images/articles/

Thanks, 
-Winona

**Comment by wsalesky** [comment]
Cleaning up issue list.
