### ISSUE TITLE
Index page description

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#4]
a. expand "Beth Mardutho" to "Beth Mardutho: The Syriac Institute" and link it to http://www.bethmardutho.org (with a target on a new tab)

b. Second paragraph, in "the root hg' meaning" replace the single quote with Unicode character 02BE.

**Comment by wsalesky** [comment]
moved to app repository: https://github.com/Beth-Mardutho/hugoye-app/issues/3
