### ISSUE TITLE
Article not showing

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#49]
@wsalesky I'm trying to figure out why the "Mary as a Letter" article (H21N1Brock) isn't showing up on the index page for volume 21 (or the current issue index): https://hugoye.bethmardutho.org/volume/21

**Comment by jedwardwalters** [comment]
Also (this may be related): basically none of the webhooks are working, and some of the changes I've made over the last couple of days seem to have reverted in the repository.

**Comment by wsalesky** [comment]
Can I go ahead and change the webhooks for the development server? That will only get changes made to the dev branch? Also, I'm not sure what is going on with the missing record, it shows up locally, but not on dev. I will investigate a bit more.

**Comment by wsalesky** [comment]
Okay, the article is there. I changed this server to respond to commits to dev: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/volume/21

I will set up webhooks on the production server tonight for the master branch.

**Comment by jedwardwalters** [comment]
Okay, sounds good. Thanks!
