### ISSUE TITLE
Editors and Editorial Board Page

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#5]
1) On home page just list main editors:
General Editor
George Anton Kiraz, Beth Mardutho: The Syriac Institute

Associate Editor
J. Edward Walters, Rochester College

Book Review Editor
Ute Possekel, Harvard Divinity School

2) Create a separate editorial board page
List of board can be copied from here:
 http://www.bethmardutho.org/index.php/hugoye/editorial-board.html

**Comment by wsalesky** [comment]
moved to app. https://github.com/Beth-Mardutho/hugoye-app/issues/4
