### ISSUE TITLE
Text layout display

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#52]
We need an offset "block quotation" layout. Sometimes these will be poetic (using `<lg> and <l>`) and sometimes they will simply be prose.

For both prose and poetry, the layout should be indented on right and left, and obviously the poetic lines texts can break at the `</l>`. There should also be some padding above and below these indented quotes.

Thus far I've been encoding these with `<cit> and <quote>`.

See examples here:
poetic: https://github.com/Beth-Mardutho/hugoye-data/blob/master/data/tei/h21n1brock.xml#L168

prose:https://github.com/Beth-Mardutho/hugoye-data/blob/master/data/tei/h21n1brock.xml#L210

**Comment by wsalesky** [comment]
Review here: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/H21N1Brock
If you like it I will move it to production.

**Comment by jedwardwalters** [comment]
This looks great. I think you can go ahead and move it over. Thanks.
