### ISSUE TITLE
Error page on article

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#66]
@wsalesky This article isn't loading on the dev server:
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/H21N1Brock

It may be related to the fact that I changed the file name, but making the URL /H**V**21N1Brock also doesn't work.

**Comment by wsalesky** [comment]
It is here: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/hv21n1brock
