### ISSUE TITLE
Citation information in right-hand box

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#67]
In the right-hand about this digital text, I want to change the citation format. Here's what it looks like currently:
<img width="298" alt="screen shot 2018-07-09 at 12 15 18 pm" src="https://user-images.githubusercontent.com/11543800/42462687-f52cbdbe-8371-11e8-8595-4e5c78c02c84.png">
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/hv21n1possekel

Here's how it should read:
Ute Possekel, "Bardaisan's Influence on Late Antique Christianity." _Hugoye: Journal of Syriac Studies_ 21.1 (2018): 81-125.

Here's where you can find those other pieces of information in the header:
Volume/issue number and page numbers:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1Possekel.xml#L43
(lines 43-45 actually)

Date of publication:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1Possekel.xml#L18

**Comment by jedwardwalters** [comment]
Oh, and I meant to add: there should not be any white indentation space at the beginning of the entry (under Citation: and before the author's name).

**Comment by wsalesky** [comment]
Done.

**Comment by jedwardwalters** [comment]
Looks good. Thanks.
