### ISSUE TITLE
Bibliographic information on volume index pages

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#68]
We just need to make some small adjustments to the appearance of bibliographic information on the volume index pages. Here's an image with some annotation:
<img width="1354" alt="screen shot 2018-07-09 at 12 12 08 pm" src="https://user-images.githubusercontent.com/11543800/42464148-367ebeb2-8376-11e8-9a14-06fb32cbcea2.png">
Please let me know if any of this doesn't make sense.

**Comment by jedwardwalters** [comment]
One follow up: can we make the subtitle appear as part of the linked title name? It's currently encoded like this:
```
<titleStmt>
                <title type="main">Mary as a 'Letter'</title>
                <title type="sub">And Some Other Letter Imagery in Syriac Liturgical Texts
                </title>
```
One problem that I may have to deal with is that some of the subtitles have footnotes at the end, and I'll have to decide how to deal with those so that they don't appear in volume index pages, search results, etc.

**Comment by jedwardwalters** [comment]
If it's easier for you, we could probably just drop the title type distinction have the whole thing appear in as a `<title>` like this:
`<title>Mary as a 'Letter': And Some Other Letter Imagery in Syriac Liturgical Texts </title>`

**Comment by jedwardwalters** [comment]
I'm not sure that the main/sub title distinction does anything useful for us, so it may just be unnecessary baggage.

**Comment by wsalesky** [comment]
@jedwardwalters it is easy enough to suppress the footnotes. I will do that tonight.

**Comment by wsalesky** [comment]
There is an issue with the author display in 
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/hv21n1penn
I think there should be a separate `tei:author` element for each author, this will then display correctly.

**Comment by wsalesky** [comment]
Updated display: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/volumes.html

**Comment by jedwardwalters** [comment]
Okay, I can make that change for the author element. Otherwise this looks good. Thanks.

**Comment by jedwardwalters** [comment]
(I'll leave this open until I make that change)

**Comment by jedwardwalters** [comment]
Made the change to the author element in the hv21n1penn article. The volume page is only showing 3 of the 5 authors. This is the only article I can think of that has more than 3 authors, so that may not be a big deal.
