### ISSUE TITLE
Code for images

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#71]
@wsalesky Do you have a preferred encoding method for making images appear?
Here's an example of how I did a test:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1CR-Amsterdam.xml#L84

Any suggestions? I assume that cm is not the best way to do height/width. So how should we do that?

**Comment by wsalesky** [comment]
@jedwardwalters For an the URL I think we need an actual url to the image: 

`https://hugoye.bethmardutho.org/resources/images/articles/image-name.jpg`

I will most likely be loading them from github, but I will do that swap when I display the html. I think we should use pixels for the height/width, not sure if you want to convert the existing measurements to pixels. If not we could just have a standard size we use if the measurements are not pixels (in the xslt)

**Comment by jedwardwalters** [comment]
@wsalesky I put full URL links for images into this article as a test, but they aren't visible yet. Just letting you know so you have something to test with:
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/report/hv21n1cr-amsterdam

See code here:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1CR-Amsterdam.xml#L146

Let me know if I don't have the encoding right.

**Comment by jedwardwalters** [comment]
Also, I used a "caption" element, so maybe we can add some styling for that. I used a rend attribute:
https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1CR-Amsterdam.xml#L148

**Comment by wsalesky** [comment]
Added.
