### ISSUE TITLE
Superscript

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#73]
@wsalesky I've been marking up an article that has some superscript characters. From my perusal of the TEI guidelines, there doesn't seem to be a standard protocol for this. So, I googled around and went with what seems to be the most common method:
`<hi rend="sup">[text to be superscript]</hi>`

So, whenever you get a chance, if you could set up that display feature, that would be great.

**Comment by wsalesky** [comment]
Add 'sub' and 'sup' to `tei:hi` render.

**Comment by jedwardwalters** [comment]
The xml document for the file I was testing this on is on github (https://github.com/Beth-Mardutho/hugoye-data/blob/dev/data/tei/HV21N1PRJuckel.xml), but I think the webhook from when I added it failed because it's not available for viewing yet.

**Comment by wsalesky** [comment]
This is up now: http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/review/hv21n1prjuckel

**Comment by jedwardwalters** [comment]
Superscript text all looks great.
