### ISSUE TITLE
Sedra box

### ISSUE THREAD

**Issue by jedwardwalters** [Beth-Mardutho/hugoye-data#81]
@gkiraz @wsalesky  Is the SEDRA box supposed to be stationary in the top right corner? Did we talk about it at some point? 

It works fine as is, but having it stationary means you'll have to scroll up to the top of the page every time you click on a word. You can view/test it here:
http://wwwb.library.vanderbilt.edu/exist/apps/hugoye/article/hv21n1kessel

**Comment by wsalesky** [comment]
No, that is a bug. I will look into it.

**Comment by wsalesky** [comment]
Fixed

**Comment by jedwardwalters** [comment]
Thanks.
