### ISSUE TITLE
GAK-eval Top-right buttons

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#86]
TEI button: gives error

PDF button gives error

![image](https://user-images.githubusercontent.com/9748044/42729655-d5671cec-87ac-11e8-86ea-0eed5580a57b.png)

**Comment by wsalesky** [comment]
@gkiraz TEI is fixed and PDF will be fixed when the PDF is pushed to the master branch. 
FYI @jedwardwalters
