### ISSUE TITLE
GAK-eval Links to GEDSH when available

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#93]
For items that we have GEDSH articles, our links should go to GEDSH not to Syriaca.org because there is more interesting content for our Hugoye readers there. The GEDSH article already points to Syriaca and people can go there.

I don't us having Syriaca as a secondary link of course. But the main link from the body of the text should go to GEDSH when possible.

![image](https://user-images.githubusercontent.com/9748044/42729740-d03ece1a-87af-11e8-88ac-720c4073cf31.png)

**Comment by jedwardwalters** [comment]
@gkiraz Yes, I'm working on this. We only had links to Syriaca in that one article as a test run. I have already switched them over (though it's not displaying just yet because of a webhook).
