### ISSUE TITLE
GAK-eval footer text color

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#94]
@wsalesky , do you think we should reverse the color of the linked/unlinked texts in the footer?

But, you are the color person, so it is really your call.

![image](https://user-images.githubusercontent.com/9748044/42729749-6756c9ba-87b0-11e8-9716-f52ab5a75f4b.png)

**Comment by jedwardwalters** [comment]
I have no opinion on this, but I'm fine with it as is.

**Comment by wsalesky** [comment]
@gkiraz I changed it, if you like it, you may close this.

**Comment by jedwardwalters** [comment]
Looks good to me. @gkiraz, you can close this issue if it looks good to you.
