### ISSUE TITLE
GAK-eval Footnote style

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#95]
@jedwardwalters , shouldn't we be justifying footnote texts? I think we do in the print edition.

![image](https://user-images.githubusercontent.com/9748044/42729754-9e7aa204-87b0-11e8-89c7-904e0472c07b.png)

**Comment by jedwardwalters** [comment]
@wsalesky Would it fix this issue for me to add the xml:lang="en" attribute on the <p rend="footnote text"> element? If so is that the easiest way to fix it?

**Comment by wsalesky** [comment]
@jedwardwalters it is just a css issue, I will fix it.

**Comment by wsalesky** [comment]
Done.
