### ISSUE TITLE
GAK-eval Extra dotted line in Table of Contents Box

### ISSUE THREAD

**Issue by gkiraz** [Beth-Mardutho/hugoye-data#98]
1. Is it possible to have the "Table of Contents" box float with the article? (@jedwardwalters , do you think this is a good idea?)

2. Please remove extra dotted line at the end of the contents:

![image](https://user-images.githubusercontent.com/9748044/42729785-a9dae234-87b1-11e8-80d8-36db6bb5fd0e.png)

**Comment by jedwardwalters** [comment]
The floating menu isn't a bad idea, but it might mess up our mobile display. I'll let @wsalesky weigh in on that. I don't think it's necessary, but could be a nice feature if it's easy to implement for desktop display.

**Comment by wsalesky** [comment]
@gkiraz @jedwardwalters The floating TOC does mess up the mobile display. I can probably fix it with some css fiddling, but I'm going to put it on the back burner until everything else is fixed.

**Comment by jedwardwalters** [comment]
That's a good solution, @wsalesky. If we don't get around to implementing it, it's not a big deal.

**Comment by wsalesky** [comment]
Fixed.
